CREATE TABLE IF NOT EXISTS `mesVin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Nom` TEXT DEFAULT NULL,
  `Cepage` TEXT DEFAULT NULL,
  `Couleur` TEXT DEFAULT NULL,
  `Millesime` TEXT DEFAULT NULL,
  `Terroir` TEXT DEFAULT NULL,
  `DegreAlcoolique` TEXT DEFAULT NULL,
  `Vinification` TEXT DEFAULT NULL,
  `TempIdeal` TEXT DEFAULT NULL,
  `Decanter` TEXT DEFAULT NULL,
  `Volume` TEXT DEFAULT NULL,
  `Met` TEXT DEFAULT NULL,
  `Ettiquette` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;